### ISSUE TITLE
Overflow text - make it seems like there is a scroll

### ISSUE THREAD

**Issue by jackbridger** [fac-17/BELO#21]
Overflow makes me feel like the articles are scrollable

<img width="342" alt="Screenshot 2019-08-02 at 10 06 26" src="https://user-images.githubusercontent.com/7283908/62358768-49456e00-b50d-11e9-8839-849ee29e3e6d.png">

**Comment by Oliversw** [comment]
Also for all of the articles the text in italics is the same as the text underneath. Might be worth looking into!
