### ISSUE TITLE
handlePublic

### ISSUE THREAD

**Issue by Baalwaan** [fac-17/BELO#27]
I see what you did there! 

I like how you have one handler to serve your entire client side code. 

Efficient and 
![](https://media1.giphy.com/media/d3mlE7uhX8KFgEmY/giphy.gif?cid=790b76115d43ff364b735652327d591d&rid=giphy.gif])

**Comment by emaggy** [comment]
Thanks 

![](https://media2.giphy.com/media/xTg8APb2xRG2wdTCs8/giphy.gif?cid=790b76115d440c1874574373518f2396&rid=giphy.gif)
